---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/mydatar1/mydatar1.csv
    type: table
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/278401/master/file/figures/mydatar1/mydatar1.csv"
    folder_url: "/users/2191/articles/278401/master/folder/figures/mydatar1"
