---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/GW455H312/GW455H312.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/2191/articles/278401/master/file/figures/GW455H312/GW455H312.png"
    folder_url: "/users/2191/articles/278401/master/folder/figures/GW455H312"
